# Site settings
title: Anaquash
email: #your-email@domain.com
url: https://beckyharlan.github.io
description: "The Anacostia River derived its name from the Nacotchtank word Anaquash, which means “village trading center.” This is a photographic exploration of the Anacostia as an epicenter for community in Washington, D.C. Meet the people who have loved the river through its hard times—the people who treat its banks like a front porch, those who fish and kayak in its waters, and those who are tirelessly working to restore balance to the ecosystem."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#262626'
  links: '#219ab3'

# Footer settings
footer: Becky Harlan

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
